development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:7be4e5d02b1848aa732193865a595be4@pike.redistogo.com:9432/
  channel_prefix: PixeLove_production
